### ISSUE TITLE
Theming question

### ISSUE THREAD

**Issue by jscottelblein** [JulianPrieber/llc-themes#3]
Heyas

So I'm playing around with making a [Nord](https://www.nordtheme.com/) theme:

![image](https://user-images.githubusercontent.com/1524526/186395687-7fd49d0b-d540-43c3-8dc2-78b879458c8c.png)

and ran into a little bit of confusion. It appears that not all of the css files needing to be changed exist in the template? (or am I doing it wrong?):

Template:

https://github.com/STaRDoGG/llc-default

Actual (includes 3 extra files):

https://github.com/JulianPrieber/littlelink-custom/tree/main/littlelink/css

Also, when playing around changing colors in the dev inspector I can see that some of the colors are coming from:

`/studio/css/style-dashboard-dark.css`

and on the login page is:

`/css/app-dark.css`

I can make *some* changes in the template files and have them take effect (mainly on the home page) but it seems all of the colors in the admin area are in a css that isn't in the template?

**Comment by JulianPrieber** [comment]
Hi,

> and ran into a little bit of confusion. It appears that not all of the css files needing to be changed exist in the template? (or am I doing it wrong?):

Everything that can be changed is included in the template repository.

Themes only apply to the links page, not the Admin Panel or login pages.
Since the addition of the Advanced Config, themes can also be applied to the Home Page, but that's about it.

If you would like to change the theme of your Admin Panel and other pages, you'd have to edit the files you listed directly. Please note that if you were to do this, all your changes will be reset if you update your instance.


Hope this cleared things up a bit.

**Comment by jscottelblein** [comment]
Ahh ok. I was assuming Dark or Light meant throughout the whole app.

It might be a nice addition to have the ability to theme the rest as well. I'm a big fan of the Nord palette. =)

I guessing that if I just make those personal changes and mount only those edited css files to the container, it shouldn't reset anything, since they're only css files?

Right now when editing the template css files I do the same thing; just mount those css files to the container.

**Comment by JulianPrieber** [comment]
This won't reset anything. 
If the application isn't able to write to those files on update and something has been changed or added to those files, some things might not display properly, but that's about it.

**Comment by jscottelblein** [comment]
I'm guessing the css files that arent part of the template are actually part of the framework itself? And the template files are part of your app (LLC)? That's why the framework css arent part of what is changeable?

If that's the case one idea that would allow users to also theme the other stuff (the framework theme) might be how some other apps do it, like Organizr for example. It has a section in the settings for the user to add their own css, and then it just loads at the very end so it takes precedence:

![image](https://user-images.githubusercontent.com/1524526/186406965-86e60bba-a65f-4f83-ac2c-153ac91c08bc.png)

**Comment by JulianPrieber** [comment]
The theming of our Admin Panel is provided by the template, it was made from.

I had something like this in mind and briefly worked on something like this, but scrapped the idea due to the complexity involved.
I have the idea to switch to a more responsive JavaScript frontend for the Admin Panel, but until I'm certain with what I want to do with this, I'd rather not include something like this if it means where gonna change it later on.

I still want to include as much customizability as possible (hence the name...), but as it stands now, nothing is written in stone.

**Comment by jscottelblein** [comment]
Ok. Maybe I'll theme it all via css mounts, add a PR for the template, and then I dunno, maybe add a separate repo as a "Nord+" theme, or "Nord Expanded" (or whatever) that also includes the theming for the rest that other's who may be interested can mount separately via docker mounts. Does that sound ok?

**Comment by JulianPrieber** [comment]
Sounds good 👍
