### ISSUE TITLE
In every Theme there is an "I" instead of an "L"

### ISSUE THREAD

**Issue by MagicLike** [JulianPrieber/llc-themes#6]
Every theme has "Theme Author URI" instead of "Theme Author URL" in it's readme

**Comment by JulianPrieber** [comment]
Oh yeah, that is actually intentional.

Technically, both would be correct here.

A URI is a string of characters used to identify a resource. URL is a subset of URI that specifies the location of a resource.
So this would include something like a twitter handle as well.


I used a URI instead of a URL because it is more general and can be used to identify any type of resource.




 ![2](https://user-images.githubusercontent.com/60265788/190107850-6ab56fae-9842-4907-9c50-518ed9b84b46.png)  | ![1](https://user-images.githubusercontent.com/60265788/190107853-98f788cd-0993-4c91-a0c0-857e0bf8ec13.png)
------------ | -------------
